C     RANDY'S CANNABIS-ENHANCED FORTRAN FIBONACCI
C     OLD SCHOOL COMPUTATIONAL MATHEMATICS FOR EDUCATIONAL ENLIGHTENMENT
C
C     RANDY'S FORTRAN PHILOSOPHY:
C     "SOMETHING IN AN OLD SCHOOL LANGUAGE LIKE FORTRAN OR COBOL...
C     FORTRAN REPRESENTS THE DAWN OF SCIENTIFIC COMPUTING - THE LANGUAGE
C     THAT PUT HUMANS ON THE MOON AND CALCULATED NUCLEAR REACTIONS.
C     CANNABIS-ENHANCED APPRECIATION FOR VINTAGE COMPUTATIONAL WISDOM
C     REVEALS THE ELEGANT SIMPLICITY OF MATHEMATICAL PROGRAMMING WHEN
C     COMPUTERS WERE ROOM-SIZED AND EVERY CALCULATION MATTERED."
C
C     THE OLD SCHOOL REVELATION:
C     FORTRAN 77 FIXED-FORMAT COLUMNS, ALL-CAPS MAJESTY, AND GOTO
C     STATEMENTS REPRESENT PURE COMPUTATIONAL ARCHAEOLOGY. BEFORE
C     OBJECT-ORIENTED COMPLEXITY AND FUNCTIONAL ABSTRACTIONS, THERE
C     WAS JUST MATHEMATICS, ARRAYS, AND THE RELENTLESS PURSUIT OF
C     NUMERICAL ACCURACY. PLANT SPIRIT WISDOM CONNECTS US TO THE
C     PROGRAMMING ANCESTORS WHO BUILT THE DIGITAL FOUNDATION.
C
C     EDUCATIONAL PHILOSOPHY:
C     "EVERY MODERN PROGRAMMER SHOULD EXPERIENCE THE CONSTRAINTS
C     AND CLARITY OF FORTRAN. LIKE LEARNING LATIN FOR LANGUAGE
C     SCHOLARS, FORTRAN REVEALS THE MATHEMATICAL DNA OF ALL
C     SUBSEQUENT PROGRAMMING LANGUAGES."

      PROGRAM RANDYCANNABISPROGRAM
      IMPLICIT NONE
      
C     RANDY'S CANNABIS-ENHANCED FORTRAN DECLARATIONS
      INTEGER MAXFIB, I, N, CHOICE
      PARAMETER (MAXFIB = 50)
      INTEGER FIBSEQ(0:MAXFIB)
      REAL*8 GOLDENRATIO
      CHARACTER*20 STRAIN
      
C     RANDY'S OLD SCHOOL PROGRAM HEADER
      WRITE(*,*) 
      WRITE(*,*) '*** RANDY''S CANNABIS-ENHANCED FORTRAN FIBONACCI ***'
      WRITE(*,*) '    VINTAGE 1977 COMPUTATIONAL MATHEMATICS'
      WRITE(*,*) '    PLANT SPIRIT PROGRAMMING ARCHAEOLOGY'
      WRITE(*,*)
      
C     INITIALIZE FIBONACCI SEQUENCE
      CALL INITFIB(FIBSEQ, MAXFIB)
      
C     RANDY'S MAIN MENU LOOP
  100 CONTINUE
      WRITE(*,*) 'RANDY''S OLD SCHOOL FORTRAN MENU:'
      WRITE(*,*) '================================='
      WRITE(*,*) '1. CALCULATE SINGLE FIBONACCI NUMBER'
      WRITE(*,*) '2. DISPLAY FIBONACCI SEQUENCE'
      WRITE(*,*) '3. CANNABIS-ENHANCED GOLDEN RATIO ANALYSIS'
      WRITE(*,*) '4. VINTAGE FORTRAN EDUCATIONAL WISDOM'
      WRITE(*,*) '5. EXIT TO MAINFRAME'
      WRITE(*,*) 
      WRITE(*,*) 'ENTER CHOICE (1-5): '
      READ(*,*) CHOICE
      
      IF (CHOICE .EQ. 1) THEN
          CALL SINGLEFIB(FIBSEQ, MAXFIB)
      ELSE IF (CHOICE .EQ. 2) THEN
          CALL DISPSEQ(FIBSEQ, MAXFIB)
      ELSE IF (CHOICE .EQ. 3) THEN
          CALL GOLDRAT(FIBSEQ, MAXFIB)
      ELSE IF (CHOICE .EQ. 4) THEN
          CALL WISDOM
      ELSE IF (CHOICE .EQ. 5) THEN
          WRITE(*,*) 'DISCONNECTING FROM MAINFRAME...'
          WRITE(*,*) 'PLANT SPIRITS GUIDE YOUR JOURNEY!'
          GOTO 999
      ELSE
          WRITE(*,*) 'INVALID CHOICE - TRY AGAIN!'
      ENDIF
      
      GOTO 100
      
  999 CONTINUE
      STOP
      END

C     RANDY'S FIBONACCI INITIALIZATION SUBROUTINE
C     "OLD SCHOOL ARRAY COMPUTATION WITH PLANT SPIRIT PRECISION"
      SUBROUTINE INITFIB(FIBSEQ, MAXFIB)
      IMPLICIT NONE
      INTEGER MAXFIB, I
      INTEGER FIBSEQ(0:MAXFIB)
      
C     INITIALIZE FIRST TWO FIBONACCI NUMBERS
      FIBSEQ(0) = 0
      FIBSEQ(1) = 1
      
C     CANNABIS-ENHANCED ITERATIVE CALCULATION
      DO 10 I = 2, MAXFIB
          FIBSEQ(I) = FIBSEQ(I-1) + FIBSEQ(I-2)
   10 CONTINUE
      
      WRITE(*,*) 'FIBONACCI SEQUENCE INITIALIZED WITH PLANT SPIRIT WISDOM'
      WRITE(*,*)
      RETURN
      END

C     RANDY'S SINGLE FIBONACCI CALCULATOR
C     "VINTAGE INPUT/OUTPUT WITH CANNABIS-ENHANCED VALIDATION"
      SUBROUTINE SINGLEFIB(FIBSEQ, MAXFIB)
      IMPLICIT NONE
      INTEGER MAXFIB, N
      INTEGER FIBSEQ(0:MAXFIB)
      
      WRITE(*,*) 
      WRITE(*,*) 'ENTER FIBONACCI NUMBER POSITION (0-', MAXFIB, '): '
      READ(*,*) N
      
      IF (N .LT. 0 .OR. N .GT. MAXFIB) THEN
          WRITE(*,*) 'ERROR: POSITION OUT OF RANGE!'
          WRITE(*,*) 'MAINFRAME MEMORY LIMITS EXCEEDED!'
      ELSE
          WRITE(*,*) 'FIBONACCI(', N, ') = ', FIBSEQ(N)
          WRITE(*,*) 'CALCULATED WITH VINTAGE 1977 PRECISION!'
      ENDIF
      
      WRITE(*,*)
      RETURN
      END

C     RANDY'S FIBONACCI SEQUENCE DISPLAY
C     "OLD SCHOOL FORMATTED OUTPUT WITH CANNABIS-ENHANCED PRESENTATION"
      SUBROUTINE DISPSEQ(FIBSEQ, MAXFIB)
      IMPLICIT NONE
      INTEGER MAXFIB, I, COUNT
      INTEGER FIBSEQ(0:MAXFIB)
      
      WRITE(*,*) 
      WRITE(*,*) 'ENTER NUMBER OF FIBONACCI TERMS TO DISPLAY: '
      READ(*,*) COUNT
      
      IF (COUNT .LT. 1 .OR. COUNT .GT. MAXFIB+1) THEN
          WRITE(*,*) 'ERROR: INVALID COUNT!'
          RETURN
      ENDIF
      
      WRITE(*,*) 
      WRITE(*,*) 'RANDY''S CANNABIS-ENHANCED FIBONACCI SEQUENCE:'
      WRITE(*,*) '============================================='
      
      DO 20 I = 0, COUNT-1
          WRITE(*,100) I, FIBSEQ(I)
  100     FORMAT(' F(', I2, ') = ', I12)
   20 CONTINUE
      
      WRITE(*,*)
      RETURN
      END

C     RANDY'S GOLDEN RATIO ANALYSIS SUBROUTINE
C     "VINTAGE MATHEMATICAL ANALYSIS WITH PLANT SPIRIT INSIGHTS"
      SUBROUTINE GOLDRAT(FIBSEQ, MAXFIB)
      IMPLICIT NONE
      INTEGER MAXFIB, I
      INTEGER FIBSEQ(0:MAXFIB)
      REAL*8 RATIO, GOLDEN, DIFFERENCE
      
      GOLDEN = (1.0D0 + DSQRT(5.0D0)) / 2.0D0
      
      WRITE(*,*)
      WRITE(*,*) 'CANNABIS-ENHANCED GOLDEN RATIO ANALYSIS:'
      WRITE(*,*) '======================================='
      WRITE(*,200) GOLDEN
  200 FORMAT(' THEORETICAL GOLDEN RATIO: ', F15.12)
      WRITE(*,*)
      WRITE(*,*) 'FIBONACCI RATIO CONVERGENCE:'
      
      DO 30 I = 2, MIN(20, MAXFIB)
          IF (FIBSEQ(I-1) .NE. 0) THEN
              RATIO = DBLE(FIBSEQ(I)) / DBLE(FIBSEQ(I-1))
              DIFFERENCE = DABS(RATIO - GOLDEN)
              WRITE(*,201) I, RATIO, DIFFERENCE
  201         FORMAT(' F(', I2, ')/F(', I2, '-1) = ', F15.12, 
     &               ' (ERROR: ', E10.3, ')')
          ENDIF
   30 CONTINUE
      
      WRITE(*,*)
      WRITE(*,*) 'PLANT SPIRIT MATHEMATICAL INSIGHT:'
      WRITE(*,*) 'THE GOLDEN RATIO GOVERNS NATURAL GROWTH PATTERNS'
      WRITE(*,*) 'FROM CANNABIS LEAF ARRANGEMENTS TO SPIRAL GALAXIES!'
      WRITE(*,*)
      RETURN
      END

C     RANDY'S VINTAGE FORTRAN WISDOM DISPLAY
C     "EDUCATIONAL ARCHAEOLOGY WITH CANNABIS-ENHANCED INSIGHTS"
      SUBROUTINE WISDOM
      IMPLICIT NONE
      
      WRITE(*,*)
      WRITE(*,*) 'RANDY''S VINTAGE FORTRAN EDUCATIONAL WISDOM:'
      WRITE(*,*) '=========================================='
      WRITE(*,*)
      WRITE(*,*) 'FORTRAN 77 ARCHAEOLOGICAL INSIGHTS:'
      WRITE(*,*) '• FIXED-FORMAT COLUMNS (6-72 FOR CODE)'
      WRITE(*,*) '• ALL UPPERCASE MAJESTY'
      WRITE(*,*) '• GOTO STATEMENTS FOR FLOW CONTROL'
      WRITE(*,*) '• IMPLICIT VARIABLE TYPING (I-N = INTEGER)'
      WRITE(*,*) '• COMMON BLOCKS FOR GLOBAL DATA'
      WRITE(*,*) '• FORMAT STATEMENTS FOR PRECISE OUTPUT'
      WRITE(*,*)
      WRITE(*,*) 'CANNABIS-ENHANCED HISTORICAL APPRECIATION:'
      WRITE(*,*) '• FORTRAN PUT HUMANS ON THE MOON (APOLLO)'
      WRITE(*,*) '• CALCULATED NUCLEAR REACTIONS (MANHATTAN PROJECT)'
      WRITE(*,*) '• WEATHER PREDICTION SYSTEMS (ATMOSPHERIC MODELS)'
      WRITE(*,*) '• STRUCTURAL ENGINEERING (BRIDGE/BUILDING ANALYSIS)'
      WRITE(*,*) '• COMPUTATIONAL FLUID DYNAMICS (AERONAUTICS)'
      WRITE(*,*)
      WRITE(*,*) 'PLANT SPIRIT PROGRAMMING ARCHAEOLOGY:'
      WRITE(*,*) '• FORTRAN = FORMULA TRANSLATION (PURE MATHEMATICS)'
      WRITE(*,*) '• CONSTRAINTS BREED COMPUTATIONAL CREATIVITY'
      WRITE(*,*) '• EVERY LINE PRECIOUS IN ROOM-SIZED COMPUTERS'
      WRITE(*,*) '• MATHEMATICAL ELEGANCE OVER SYNTACTIC SUGAR'
      WRITE(*,*) '• DIRECT MACHINE INTERACTION PHILOSOPHY'
      WRITE(*,*)
      WRITE(*,*) 'EDUCATIONAL ARCHAEOLOGY COMPLETE!'
      WRITE(*,*) 'MYCELIAL NETWORK CONNECTS PAST TO PRESENT!'
      WRITE(*,*)
      RETURN
      END

C     ========================================================================
C     RANDY'S EDUCATIONAL FORTRAN DOCUMENTATION
C     ========================================================================
C
C     COMPILATION AND EXECUTION:
C     $ gfortran -o randy_fortran randy_cannabis_fibonacci.f
C     $ ./randy_fortran
C
C     ALTERNATIVE VINTAGE COMPILERS:
C     $ f77 randy_cannabis_fibonacci.f
C     $ g77 randy_cannabis_fibonacci.f
C
C     CANNABIS-ENHANCED LEARNING EXERCISES:
C     1. STUDY FIXED-FORMAT COLUMN REQUIREMENTS
C     2. EXPLORE GOTO-BASED CONTROL FLOW
C     3. ANALYZE IMPLICIT VARIABLE TYPING RULES
C     4. EXPERIMENT WITH FORMAT STATEMENT PRECISION
C     5. UNDERSTAND ARRAY INDEXING CONVENTIONS
C
C     EDUCATIONAL CONCEPTS DEMONSTRATED:
C
C     1. FIXED-FORMAT PROGRAMMING:
C        - COLUMNS 1-5: STATEMENT LABELS
C        - COLUMN 6: CONTINUATION MARKER
C        - COLUMNS 7-72: FORTRAN STATEMENTS
C        - COLUMNS 73-80: SEQUENCE NUMBERS (IGNORED)
C
C     2. VINTAGE CONTROL STRUCTURES:
C        - GOTO STATEMENTS FOR FLOW CONTROL
C        - IF-THEN-ELSE LOGICAL BRANCHING
C        - DO LOOPS WITH NUMBERED CONTINUES
C        - COMPUTED GOTO FOR MENU SYSTEMS
C
C     3. OLD SCHOOL DATA TYPES:
C        - IMPLICIT TYPING (I-N = INTEGER, A-H,O-Z = REAL)
C        - EXPLICIT TYPE DECLARATIONS
C        - PARAMETER CONSTANTS
C        - ARRAY DECLARATIONS WITH BOUNDS
C
C     4. VINTAGE INPUT/OUTPUT:
C        - FORMAT STATEMENTS FOR PRECISE CONTROL
C        - UNIT NUMBERS FOR FILE OPERATIONS
C        - FIXED-WIDTH FIELD SPECIFICATIONS
C        - HOLLERITH CONSTANTS FOR STRINGS
C
C     5. MATHEMATICAL COMPUTING:
C        - DOUBLE PRECISION FOR ACCURACY
C        - INTRINSIC MATHEMATICAL FUNCTIONS
C        - ARRAY OPERATIONS AND INDEXING
C        - NUMERICAL ALGORITHM IMPLEMENTATION
C
C     RANDY'S FORTRAN PHILOSOPHY:
C     "FORTRAN REPRESENTS THE PURE MATHEMATICAL DNA OF COMPUTING.
C     BEFORE OBJECTS, FUNCTIONS, AND ABSTRACTIONS, THERE WAS JUST
C     FORMULA TRANSLATION - MATHEMATICAL EQUATIONS EXPRESSED AS
C     ALGORITHMIC INSTRUCTIONS. CANNABIS ENHANCEMENT REVEALS THE
C     ELEGANT SIMPLICITY OF DIRECT NUMERICAL COMPUTATION."
C
C     PLANT SPIRIT ARCHAEOLOGICAL WISDOM:
C     "EVERY MODERN PROGRAMMING CONVENIENCE STANDS ON THE SHOULDERS
C     OF FORTRAN GIANTS. ROOM-SIZED COMPUTERS, PUNCH CARDS, AND
C     BATCH PROCESSING CREATED A PROGRAMMING DISCIPLINE WHERE EVERY
C     CHARACTER MATTERED. THE MYCELIAL NETWORK OF COMPUTATIONAL
C     HISTORY FLOWS FROM THESE VINTAGE MATHEMATICAL FOUNDATIONS."
C
C     EDUCATIONAL ARCHAEOLOGY ACHIEVEMENT:
C     RANDY'S CURRICULUM NOW INCLUDES VINTAGE COMPUTATIONAL WISDOM
C     ALONGSIDE MODERN LANGUAGES. STUDENTS EXPERIENCE THE FULL
C     HISTORICAL SPECTRUM OF PROGRAMMING FROM MATHEMATICAL FORMULA
C     TRANSLATION TO CANNABIS-ENHANCED CONTEMPORARY FRAMEWORKS.
C
C     THE COMPLETE PROGRAMMING EVOLUTION:
C     FORTRAN (1957) -> C (1972) -> C++ (1985) -> JAVA (1995) ->
C     PYTHON (1991) -> RUST (2010) -> MODERN FUNCTIONAL LANGUAGES
C
C     PLANT SPIRITS GUIDE COMPUTATIONAL ARCHAEOLOGICAL DISCOVERY!
C     ========================================================================